// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Deliveryinfo;
import ch.emineo.roo.reverse.domain.DeliveryinfoDataOnDemand;
import ch.emineo.roo.reverse.domain.DeliveryinfoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DeliveryinfoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DeliveryinfoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DeliveryinfoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DeliveryinfoIntegrationTest: @Transactional;
    
    @Autowired
    private DeliveryinfoDataOnDemand DeliveryinfoIntegrationTest.dod;
    
    @Test
    public void DeliveryinfoIntegrationTest.testCountDeliveryinfoes() {
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", dod.getRandomDeliveryinfo());
        long count = Deliveryinfo.countDeliveryinfoes();
        Assert.assertTrue("Counter for 'Deliveryinfo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DeliveryinfoIntegrationTest.testFindDeliveryinfo() {
        Deliveryinfo obj = dod.getRandomDeliveryinfo();
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", obj);
        Integer id = obj.getDeliveryinfoid();
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to provide an identifier", id);
        obj = Deliveryinfo.findDeliveryinfo(id);
        Assert.assertNotNull("Find method for 'Deliveryinfo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Deliveryinfo' returned the incorrect identifier", id, obj.getDeliveryinfoid());
    }
    
    @Test
    public void DeliveryinfoIntegrationTest.testFindAllDeliveryinfoes() {
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", dod.getRandomDeliveryinfo());
        long count = Deliveryinfo.countDeliveryinfoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Deliveryinfo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Deliveryinfo> result = Deliveryinfo.findAllDeliveryinfoes();
        Assert.assertNotNull("Find all method for 'Deliveryinfo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Deliveryinfo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DeliveryinfoIntegrationTest.testFindDeliveryinfoEntries() {
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", dod.getRandomDeliveryinfo());
        long count = Deliveryinfo.countDeliveryinfoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Deliveryinfo> result = Deliveryinfo.findDeliveryinfoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Deliveryinfo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Deliveryinfo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DeliveryinfoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", dod.getRandomDeliveryinfo());
        Deliveryinfo obj = dod.getNewTransientDeliveryinfo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Deliveryinfo' identifier to be null", obj.getDeliveryinfoid());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Deliveryinfo' identifier to no longer be null", obj.getDeliveryinfoid());
    }
    
    @Test
    public void DeliveryinfoIntegrationTest.testRemove() {
        Deliveryinfo obj = dod.getRandomDeliveryinfo();
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to initialize correctly", obj);
        Integer id = obj.getDeliveryinfoid();
        Assert.assertNotNull("Data on demand for 'Deliveryinfo' failed to provide an identifier", id);
        obj = Deliveryinfo.findDeliveryinfo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Deliveryinfo' with identifier '" + id + "'", Deliveryinfo.findDeliveryinfo(id));
    }
    
}
