// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Attribute;
import ch.emineo.roo.reverse.domain.AttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.Product;
import ch.emineo.roo.reverse.domain.ProductAttribute;
import ch.emineo.roo.reverse.domain.ProductAttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductAttributePK;
import ch.emineo.roo.reverse.domain.ProductDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductAttributeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductAttributeDataOnDemand: @Component;
    
    private Random ProductAttributeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductAttribute> ProductAttributeDataOnDemand.data;
    
    @Autowired
    private AttributeDataOnDemand ProductAttributeDataOnDemand.attributeDataOnDemand;
    
    @Autowired
    private ProductDataOnDemand ProductAttributeDataOnDemand.productDataOnDemand;
    
    public ProductAttribute ProductAttributeDataOnDemand.getNewTransientProductAttribute(int index) {
        ProductAttribute obj = new ProductAttribute();
        setEmbeddedIdClass(obj, index);
        setAttributesAttributeid(obj, index);
        setProductProductid(obj, index);
        return obj;
    }
    
    public void ProductAttributeDataOnDemand.setEmbeddedIdClass(ProductAttribute obj, int index) {
        Integer productProductid = new Integer(index);
        Integer idx = new Integer(index);
        
        ProductAttributePK embeddedIdClass = new ProductAttributePK(productProductid, idx);
        obj.setId(embeddedIdClass);
    }
    
    public void ProductAttributeDataOnDemand.setAttributesAttributeid(ProductAttribute obj, int index) {
        Attribute attributesAttributeid = attributeDataOnDemand.getRandomAttribute();
        obj.setAttributesAttributeid(attributesAttributeid);
    }
    
    public void ProductAttributeDataOnDemand.setProductProductid(ProductAttribute obj, int index) {
        Product productProductid = productDataOnDemand.getRandomProduct();
        obj.setProductProductid(productProductid);
    }
    
    public ProductAttribute ProductAttributeDataOnDemand.getSpecificProductAttribute(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductAttribute obj = data.get(index);
        ProductAttributePK id = obj.getId();
        return ProductAttribute.findProductAttribute(id);
    }
    
    public ProductAttribute ProductAttributeDataOnDemand.getRandomProductAttribute() {
        init();
        ProductAttribute obj = data.get(rnd.nextInt(data.size()));
        ProductAttributePK id = obj.getId();
        return ProductAttribute.findProductAttribute(id);
    }
    
    public boolean ProductAttributeDataOnDemand.modifyProductAttribute(ProductAttribute obj) {
        return false;
    }
    
    public void ProductAttributeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductAttribute.findProductAttributeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductAttribute' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductAttribute>();
        for (int i = 0; i < 10; i++) {
            ProductAttribute obj = getNewTransientProductAttribute(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
