// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Attribute;
import ch.emineo.roo.reverse.domain.AttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.Productthemecategory;
import ch.emineo.roo.reverse.domain.ProductthemecategoryAttribute;
import ch.emineo.roo.reverse.domain.ProductthemecategoryAttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductthemecategoryAttributePK;
import ch.emineo.roo.reverse.domain.ProductthemecategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductthemecategoryAttributeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductthemecategoryAttributeDataOnDemand: @Component;
    
    private Random ProductthemecategoryAttributeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductthemecategoryAttribute> ProductthemecategoryAttributeDataOnDemand.data;
    
    @Autowired
    private AttributeDataOnDemand ProductthemecategoryAttributeDataOnDemand.attributeDataOnDemand;
    
    @Autowired
    private ProductthemecategoryDataOnDemand ProductthemecategoryAttributeDataOnDemand.productthemecategoryDataOnDemand;
    
    public ProductthemecategoryAttribute ProductthemecategoryAttributeDataOnDemand.getNewTransientProductthemecategoryAttribute(int index) {
        ProductthemecategoryAttribute obj = new ProductthemecategoryAttribute();
        setEmbeddedIdClass(obj, index);
        setAttributesAttributeid(obj, index);
        setProductthemecategoryProductthemecategoryid(obj, index);
        return obj;
    }
    
    public void ProductthemecategoryAttributeDataOnDemand.setEmbeddedIdClass(ProductthemecategoryAttribute obj, int index) {
        Integer productthemecategoryProductthemecategoryid = new Integer(index);
        Integer idx = new Integer(index);
        
        ProductthemecategoryAttributePK embeddedIdClass = new ProductthemecategoryAttributePK(productthemecategoryProductthemecategoryid, idx);
        obj.setId(embeddedIdClass);
    }
    
    public void ProductthemecategoryAttributeDataOnDemand.setAttributesAttributeid(ProductthemecategoryAttribute obj, int index) {
        Attribute attributesAttributeid = attributeDataOnDemand.getRandomAttribute();
        obj.setAttributesAttributeid(attributesAttributeid);
    }
    
    public void ProductthemecategoryAttributeDataOnDemand.setProductthemecategoryProductthemecategoryid(ProductthemecategoryAttribute obj, int index) {
        Productthemecategory productthemecategoryProductthemecategoryid = productthemecategoryDataOnDemand.getRandomProductthemecategory();
        obj.setProductthemecategoryProductthemecategoryid(productthemecategoryProductthemecategoryid);
    }
    
    public ProductthemecategoryAttribute ProductthemecategoryAttributeDataOnDemand.getSpecificProductthemecategoryAttribute(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductthemecategoryAttribute obj = data.get(index);
        ProductthemecategoryAttributePK id = obj.getId();
        return ProductthemecategoryAttribute.findProductthemecategoryAttribute(id);
    }
    
    public ProductthemecategoryAttribute ProductthemecategoryAttributeDataOnDemand.getRandomProductthemecategoryAttribute() {
        init();
        ProductthemecategoryAttribute obj = data.get(rnd.nextInt(data.size()));
        ProductthemecategoryAttributePK id = obj.getId();
        return ProductthemecategoryAttribute.findProductthemecategoryAttribute(id);
    }
    
    public boolean ProductthemecategoryAttributeDataOnDemand.modifyProductthemecategoryAttribute(ProductthemecategoryAttribute obj) {
        return false;
    }
    
    public void ProductthemecategoryAttributeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductthemecategoryAttribute.findProductthemecategoryAttributeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductthemecategoryAttribute' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductthemecategoryAttribute>();
        for (int i = 0; i < 10; i++) {
            ProductthemecategoryAttribute obj = getNewTransientProductthemecategoryAttribute(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
