// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productsubcategory;
import ch.emineo.roo.reverse.domain.ProductsubcategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductsubcategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductsubcategoryDataOnDemand: @Component;
    
    private Random ProductsubcategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Productsubcategory> ProductsubcategoryDataOnDemand.data;
    
    public Productsubcategory ProductsubcategoryDataOnDemand.getNewTransientProductsubcategory(int index) {
        Productsubcategory obj = new Productsubcategory();
        setOnline(obj, index);
        setPicturepath(obj, index);
        setPublic1(obj, index);
        return obj;
    }
    
    public void ProductsubcategoryDataOnDemand.setOnline(Productsubcategory obj, int index) {
        Boolean online = true;
        obj.setOnline(online);
    }
    
    public void ProductsubcategoryDataOnDemand.setPicturepath(Productsubcategory obj, int index) {
        String picturepath = "picturepath_" + index;
        if (picturepath.length() > 255) {
            picturepath = picturepath.substring(0, 255);
        }
        obj.setPicturepath(picturepath);
    }
    
    public void ProductsubcategoryDataOnDemand.setPublic1(Productsubcategory obj, int index) {
        Boolean public1 = true;
        obj.setPublic1(public1);
    }
    
    public Productsubcategory ProductsubcategoryDataOnDemand.getSpecificProductsubcategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Productsubcategory obj = data.get(index);
        Integer id = obj.getProductsubcategoryid();
        return Productsubcategory.findProductsubcategory(id);
    }
    
    public Productsubcategory ProductsubcategoryDataOnDemand.getRandomProductsubcategory() {
        init();
        Productsubcategory obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getProductsubcategoryid();
        return Productsubcategory.findProductsubcategory(id);
    }
    
    public boolean ProductsubcategoryDataOnDemand.modifyProductsubcategory(Productsubcategory obj) {
        return false;
    }
    
    public void ProductsubcategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Productsubcategory.findProductsubcategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Productsubcategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Productsubcategory>();
        for (int i = 0; i < 10; i++) {
            Productsubcategory obj = getNewTransientProductsubcategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
