// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Attribute;
import ch.emineo.roo.reverse.domain.AttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.Productbuild;
import ch.emineo.roo.reverse.domain.ProductbuildAttribute;
import ch.emineo.roo.reverse.domain.ProductbuildAttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductbuildAttributePK;
import ch.emineo.roo.reverse.domain.ProductbuildDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductbuildAttributeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductbuildAttributeDataOnDemand: @Component;
    
    private Random ProductbuildAttributeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductbuildAttribute> ProductbuildAttributeDataOnDemand.data;
    
    @Autowired
    private AttributeDataOnDemand ProductbuildAttributeDataOnDemand.attributeDataOnDemand;
    
    @Autowired
    private ProductbuildDataOnDemand ProductbuildAttributeDataOnDemand.productbuildDataOnDemand;
    
    public ProductbuildAttribute ProductbuildAttributeDataOnDemand.getNewTransientProductbuildAttribute(int index) {
        ProductbuildAttribute obj = new ProductbuildAttribute();
        setEmbeddedIdClass(obj, index);
        setAttributesAttributeid(obj, index);
        setProductbuildProductbuildid(obj, index);
        return obj;
    }
    
    public void ProductbuildAttributeDataOnDemand.setEmbeddedIdClass(ProductbuildAttribute obj, int index) {
        Integer productbuildProductbuildid = new Integer(index);
        Integer idx = new Integer(index);
        
        ProductbuildAttributePK embeddedIdClass = new ProductbuildAttributePK(productbuildProductbuildid, idx);
        obj.setId(embeddedIdClass);
    }
    
    public void ProductbuildAttributeDataOnDemand.setAttributesAttributeid(ProductbuildAttribute obj, int index) {
        Attribute attributesAttributeid = attributeDataOnDemand.getRandomAttribute();
        obj.setAttributesAttributeid(attributesAttributeid);
    }
    
    public void ProductbuildAttributeDataOnDemand.setProductbuildProductbuildid(ProductbuildAttribute obj, int index) {
        Productbuild productbuildProductbuildid = productbuildDataOnDemand.getRandomProductbuild();
        obj.setProductbuildProductbuildid(productbuildProductbuildid);
    }
    
    public ProductbuildAttribute ProductbuildAttributeDataOnDemand.getSpecificProductbuildAttribute(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductbuildAttribute obj = data.get(index);
        ProductbuildAttributePK id = obj.getId();
        return ProductbuildAttribute.findProductbuildAttribute(id);
    }
    
    public ProductbuildAttribute ProductbuildAttributeDataOnDemand.getRandomProductbuildAttribute() {
        init();
        ProductbuildAttribute obj = data.get(rnd.nextInt(data.size()));
        ProductbuildAttributePK id = obj.getId();
        return ProductbuildAttribute.findProductbuildAttribute(id);
    }
    
    public boolean ProductbuildAttributeDataOnDemand.modifyProductbuildAttribute(ProductbuildAttribute obj) {
        return false;
    }
    
    public void ProductbuildAttributeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductbuildAttribute.findProductbuildAttributeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductbuildAttribute' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductbuildAttribute>();
        for (int i = 0; i < 10; i++) {
            ProductbuildAttribute obj = getNewTransientProductbuildAttribute(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
