// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productbuild;
import ch.emineo.roo.reverse.domain.ProductbuildDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductbuildIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductbuildIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductbuildIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductbuildIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductbuildIntegrationTest: @Transactional;
    
    @Autowired
    private ProductbuildDataOnDemand ProductbuildIntegrationTest.dod;
    
    @Test
    public void ProductbuildIntegrationTest.testCountProductbuilds() {
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", dod.getRandomProductbuild());
        long count = Productbuild.countProductbuilds();
        Assert.assertTrue("Counter for 'Productbuild' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductbuildIntegrationTest.testFindProductbuild() {
        Productbuild obj = dod.getRandomProductbuild();
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", obj);
        Integer id = obj.getProductbuildid();
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to provide an identifier", id);
        obj = Productbuild.findProductbuild(id);
        Assert.assertNotNull("Find method for 'Productbuild' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Productbuild' returned the incorrect identifier", id, obj.getProductbuildid());
    }
    
    @Test
    public void ProductbuildIntegrationTest.testFindAllProductbuilds() {
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", dod.getRandomProductbuild());
        long count = Productbuild.countProductbuilds();
        Assert.assertTrue("Too expensive to perform a find all test for 'Productbuild', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Productbuild> result = Productbuild.findAllProductbuilds();
        Assert.assertNotNull("Find all method for 'Productbuild' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Productbuild' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductbuildIntegrationTest.testFindProductbuildEntries() {
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", dod.getRandomProductbuild());
        long count = Productbuild.countProductbuilds();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Productbuild> result = Productbuild.findProductbuildEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Productbuild' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Productbuild' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductbuildIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", dod.getRandomProductbuild());
        Productbuild obj = dod.getNewTransientProductbuild(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Productbuild' identifier to be null", obj.getProductbuildid());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Productbuild' identifier to no longer be null", obj.getProductbuildid());
    }
    
    @Test
    public void ProductbuildIntegrationTest.testRemove() {
        Productbuild obj = dod.getRandomProductbuild();
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to initialize correctly", obj);
        Integer id = obj.getProductbuildid();
        Assert.assertNotNull("Data on demand for 'Productbuild' failed to provide an identifier", id);
        obj = Productbuild.findProductbuild(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Productbuild' with identifier '" + id + "'", Productbuild.findProductbuild(id));
    }
    
}
