// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductsubcategoryProduct;
import ch.emineo.roo.reverse.domain.ProductsubcategoryProductDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductsubcategoryProductIntegrationTest;
import ch.emineo.roo.reverse.domain.ProductsubcategoryProductPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductsubcategoryProductIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductsubcategoryProductIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductsubcategoryProductIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductsubcategoryProductIntegrationTest: @Transactional;
    
    @Autowired
    private ProductsubcategoryProductDataOnDemand ProductsubcategoryProductIntegrationTest.dod;
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testCountProductsubcategoryProducts() {
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", dod.getRandomProductsubcategoryProduct());
        long count = ProductsubcategoryProduct.countProductsubcategoryProducts();
        Assert.assertTrue("Counter for 'ProductsubcategoryProduct' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testFindProductsubcategoryProduct() {
        ProductsubcategoryProduct obj = dod.getRandomProductsubcategoryProduct();
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", obj);
        ProductsubcategoryProductPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to provide an identifier", id);
        obj = ProductsubcategoryProduct.findProductsubcategoryProduct(id);
        Assert.assertNotNull("Find method for 'ProductsubcategoryProduct' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductsubcategoryProduct' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testFindAllProductsubcategoryProducts() {
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", dod.getRandomProductsubcategoryProduct());
        long count = ProductsubcategoryProduct.countProductsubcategoryProducts();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductsubcategoryProduct', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductsubcategoryProduct> result = ProductsubcategoryProduct.findAllProductsubcategoryProducts();
        Assert.assertNotNull("Find all method for 'ProductsubcategoryProduct' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductsubcategoryProduct' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testFindProductsubcategoryProductEntries() {
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", dod.getRandomProductsubcategoryProduct());
        long count = ProductsubcategoryProduct.countProductsubcategoryProducts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductsubcategoryProduct> result = ProductsubcategoryProduct.findProductsubcategoryProductEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductsubcategoryProduct' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductsubcategoryProduct' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", dod.getRandomProductsubcategoryProduct());
        ProductsubcategoryProduct obj = dod.getNewTransientProductsubcategoryProduct(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductsubcategoryProduct' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductsubcategoryProductIntegrationTest.testRemove() {
        ProductsubcategoryProduct obj = dod.getRandomProductsubcategoryProduct();
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to initialize correctly", obj);
        ProductsubcategoryProductPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductsubcategoryProduct' failed to provide an identifier", id);
        obj = ProductsubcategoryProduct.findProductsubcategoryProduct(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductsubcategoryProduct' with identifier '" + id + "'", ProductsubcategoryProduct.findProductsubcategoryProduct(id));
    }
    
}
