// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholder;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholderDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholderIntegrationTest;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholderPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductthemesubcategoryProductthemecontentholderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductthemesubcategoryProductthemecontentholderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductthemesubcategoryProductthemecontentholderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductthemesubcategoryProductthemecontentholderIntegrationTest: @Transactional;
    
    @Autowired
    private ProductthemesubcategoryProductthemecontentholderDataOnDemand ProductthemesubcategoryProductthemecontentholderIntegrationTest.dod;
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testCountProductthemesubcategoryProductthemecontentholders() {
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", dod.getRandomProductthemesubcategoryProductthemecontentholder());
        long count = ProductthemesubcategoryProductthemecontentholder.countProductthemesubcategoryProductthemecontentholders();
        Assert.assertTrue("Counter for 'ProductthemesubcategoryProductthemecontentholder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testFindProductthemesubcategoryProductthemecontentholder() {
        ProductthemesubcategoryProductthemecontentholder obj = dod.getRandomProductthemesubcategoryProductthemecontentholder();
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", obj);
        ProductthemesubcategoryProductthemecontentholderPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to provide an identifier", id);
        obj = ProductthemesubcategoryProductthemecontentholder.findProductthemesubcategoryProductthemecontentholder(id);
        Assert.assertNotNull("Find method for 'ProductthemesubcategoryProductthemecontentholder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductthemesubcategoryProductthemecontentholder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testFindAllProductthemesubcategoryProductthemecontentholders() {
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", dod.getRandomProductthemesubcategoryProductthemecontentholder());
        long count = ProductthemesubcategoryProductthemecontentholder.countProductthemesubcategoryProductthemecontentholders();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductthemesubcategoryProductthemecontentholder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductthemesubcategoryProductthemecontentholder> result = ProductthemesubcategoryProductthemecontentholder.findAllProductthemesubcategoryProductthemecontentholders();
        Assert.assertNotNull("Find all method for 'ProductthemesubcategoryProductthemecontentholder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductthemesubcategoryProductthemecontentholder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testFindProductthemesubcategoryProductthemecontentholderEntries() {
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", dod.getRandomProductthemesubcategoryProductthemecontentholder());
        long count = ProductthemesubcategoryProductthemecontentholder.countProductthemesubcategoryProductthemecontentholders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductthemesubcategoryProductthemecontentholder> result = ProductthemesubcategoryProductthemecontentholder.findProductthemesubcategoryProductthemecontentholderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductthemesubcategoryProductthemecontentholder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductthemesubcategoryProductthemecontentholder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", dod.getRandomProductthemesubcategoryProductthemecontentholder());
        ProductthemesubcategoryProductthemecontentholder obj = dod.getNewTransientProductthemesubcategoryProductthemecontentholder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductthemesubcategoryProductthemecontentholder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductthemesubcategoryProductthemecontentholderIntegrationTest.testRemove() {
        ProductthemesubcategoryProductthemecontentholder obj = dod.getRandomProductthemesubcategoryProductthemecontentholder();
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to initialize correctly", obj);
        ProductthemesubcategoryProductthemecontentholderPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductthemesubcategoryProductthemecontentholder' failed to provide an identifier", id);
        obj = ProductthemesubcategoryProductthemecontentholder.findProductthemesubcategoryProductthemecontentholder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductthemesubcategoryProductthemecontentholder' with identifier '" + id + "'", ProductthemesubcategoryProductthemecontentholder.findProductthemesubcategoryProductthemecontentholder(id));
    }
    
}
