// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productthemecategory;
import ch.emineo.roo.reverse.domain.ProductthemecategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductthemecategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductthemecategoryDataOnDemand: @Component;
    
    private Random ProductthemecategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Productthemecategory> ProductthemecategoryDataOnDemand.data;
    
    public Productthemecategory ProductthemecategoryDataOnDemand.getNewTransientProductthemecategory(int index) {
        Productthemecategory obj = new Productthemecategory();
        setOnline(obj, index);
        setPublic1(obj, index);
        return obj;
    }
    
    public void ProductthemecategoryDataOnDemand.setOnline(Productthemecategory obj, int index) {
        Boolean online = true;
        obj.setOnline(online);
    }
    
    public void ProductthemecategoryDataOnDemand.setPublic1(Productthemecategory obj, int index) {
        Boolean public1 = true;
        obj.setPublic1(public1);
    }
    
    public Productthemecategory ProductthemecategoryDataOnDemand.getSpecificProductthemecategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Productthemecategory obj = data.get(index);
        Integer id = obj.getProductthemecategoryid();
        return Productthemecategory.findProductthemecategory(id);
    }
    
    public Productthemecategory ProductthemecategoryDataOnDemand.getRandomProductthemecategory() {
        init();
        Productthemecategory obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getProductthemecategoryid();
        return Productthemecategory.findProductthemecategory(id);
    }
    
    public boolean ProductthemecategoryDataOnDemand.modifyProductthemecategory(Productthemecategory obj) {
        return false;
    }
    
    public void ProductthemecategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Productthemecategory.findProductthemecategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Productthemecategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Productthemecategory>();
        for (int i = 0; i < 10; i++) {
            Productthemecategory obj = getNewTransientProductthemecategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
