// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategory;
import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategoryDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategoryIntegrationTest;
import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategoryPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductcategoryProductsubcategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductcategoryProductsubcategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductcategoryProductsubcategoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductcategoryProductsubcategoryIntegrationTest: @Transactional;
    
    @Autowired
    private ProductcategoryProductsubcategoryDataOnDemand ProductcategoryProductsubcategoryIntegrationTest.dod;
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testCountProductcategoryProductsubcategorys() {
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", dod.getRandomProductcategoryProductsubcategory());
        long count = ProductcategoryProductsubcategory.countProductcategoryProductsubcategorys();
        Assert.assertTrue("Counter for 'ProductcategoryProductsubcategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testFindProductcategoryProductsubcategory() {
        ProductcategoryProductsubcategory obj = dod.getRandomProductcategoryProductsubcategory();
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", obj);
        ProductcategoryProductsubcategoryPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to provide an identifier", id);
        obj = ProductcategoryProductsubcategory.findProductcategoryProductsubcategory(id);
        Assert.assertNotNull("Find method for 'ProductcategoryProductsubcategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductcategoryProductsubcategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testFindAllProductcategoryProductsubcategorys() {
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", dod.getRandomProductcategoryProductsubcategory());
        long count = ProductcategoryProductsubcategory.countProductcategoryProductsubcategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductcategoryProductsubcategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductcategoryProductsubcategory> result = ProductcategoryProductsubcategory.findAllProductcategoryProductsubcategorys();
        Assert.assertNotNull("Find all method for 'ProductcategoryProductsubcategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductcategoryProductsubcategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testFindProductcategoryProductsubcategoryEntries() {
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", dod.getRandomProductcategoryProductsubcategory());
        long count = ProductcategoryProductsubcategory.countProductcategoryProductsubcategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductcategoryProductsubcategory> result = ProductcategoryProductsubcategory.findProductcategoryProductsubcategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductcategoryProductsubcategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductcategoryProductsubcategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", dod.getRandomProductcategoryProductsubcategory());
        ProductcategoryProductsubcategory obj = dod.getNewTransientProductcategoryProductsubcategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductcategoryProductsubcategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductcategoryProductsubcategoryIntegrationTest.testRemove() {
        ProductcategoryProductsubcategory obj = dod.getRandomProductcategoryProductsubcategory();
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to initialize correctly", obj);
        ProductcategoryProductsubcategoryPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductcategoryProductsubcategory' failed to provide an identifier", id);
        obj = ProductcategoryProductsubcategory.findProductcategoryProductsubcategory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductcategoryProductsubcategory' with identifier '" + id + "'", ProductcategoryProductsubcategory.findProductcategoryProductsubcategory(id));
    }
    
}
