// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Producttheme;
import ch.emineo.roo.reverse.domain.ProductthemeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductthemeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductthemeDataOnDemand: @Component;
    
    private Random ProductthemeDataOnDemand.rnd = new SecureRandom();
    
    private List<Producttheme> ProductthemeDataOnDemand.data;
    
    public Producttheme ProductthemeDataOnDemand.getNewTransientProducttheme(int index) {
        Producttheme obj = new Producttheme();
        setOnline(obj, index);
        setPicturepath(obj, index);
        setPublic1(obj, index);
        return obj;
    }
    
    public void ProductthemeDataOnDemand.setOnline(Producttheme obj, int index) {
        Boolean online = true;
        obj.setOnline(online);
    }
    
    public void ProductthemeDataOnDemand.setPicturepath(Producttheme obj, int index) {
        String picturepath = "picturepath_" + index;
        if (picturepath.length() > 255) {
            picturepath = picturepath.substring(0, 255);
        }
        obj.setPicturepath(picturepath);
    }
    
    public void ProductthemeDataOnDemand.setPublic1(Producttheme obj, int index) {
        Boolean public1 = true;
        obj.setPublic1(public1);
    }
    
    public Producttheme ProductthemeDataOnDemand.getSpecificProducttheme(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Producttheme obj = data.get(index);
        Integer id = obj.getProductthemeid();
        return Producttheme.findProducttheme(id);
    }
    
    public Producttheme ProductthemeDataOnDemand.getRandomProducttheme() {
        init();
        Producttheme obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getProductthemeid();
        return Producttheme.findProducttheme(id);
    }
    
    public boolean ProductthemeDataOnDemand.modifyProducttheme(Producttheme obj) {
        return false;
    }
    
    public void ProductthemeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Producttheme.findProductthemeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Producttheme' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Producttheme>();
        for (int i = 0; i < 10; i++) {
            Producttheme obj = getNewTransientProducttheme(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
