// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productsubcategory;
import ch.emineo.roo.reverse.domain.ProductsubcategoryDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductsubcategoryIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductsubcategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductsubcategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductsubcategoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductsubcategoryIntegrationTest: @Transactional;
    
    @Autowired
    private ProductsubcategoryDataOnDemand ProductsubcategoryIntegrationTest.dod;
    
    @Test
    public void ProductsubcategoryIntegrationTest.testCountProductsubcategorys() {
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", dod.getRandomProductsubcategory());
        long count = Productsubcategory.countProductsubcategorys();
        Assert.assertTrue("Counter for 'Productsubcategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductsubcategoryIntegrationTest.testFindProductsubcategory() {
        Productsubcategory obj = dod.getRandomProductsubcategory();
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", obj);
        Integer id = obj.getProductsubcategoryid();
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to provide an identifier", id);
        obj = Productsubcategory.findProductsubcategory(id);
        Assert.assertNotNull("Find method for 'Productsubcategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Productsubcategory' returned the incorrect identifier", id, obj.getProductsubcategoryid());
    }
    
    @Test
    public void ProductsubcategoryIntegrationTest.testFindAllProductsubcategorys() {
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", dod.getRandomProductsubcategory());
        long count = Productsubcategory.countProductsubcategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Productsubcategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Productsubcategory> result = Productsubcategory.findAllProductsubcategorys();
        Assert.assertNotNull("Find all method for 'Productsubcategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Productsubcategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductsubcategoryIntegrationTest.testFindProductsubcategoryEntries() {
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", dod.getRandomProductsubcategory());
        long count = Productsubcategory.countProductsubcategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Productsubcategory> result = Productsubcategory.findProductsubcategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Productsubcategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Productsubcategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductsubcategoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", dod.getRandomProductsubcategory());
        Productsubcategory obj = dod.getNewTransientProductsubcategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Productsubcategory' identifier to be null", obj.getProductsubcategoryid());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Productsubcategory' identifier to no longer be null", obj.getProductsubcategoryid());
    }
    
    @Test
    public void ProductsubcategoryIntegrationTest.testRemove() {
        Productsubcategory obj = dod.getRandomProductsubcategory();
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to initialize correctly", obj);
        Integer id = obj.getProductsubcategoryid();
        Assert.assertNotNull("Data on demand for 'Productsubcategory' failed to provide an identifier", id);
        obj = Productsubcategory.findProductsubcategory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Productsubcategory' with identifier '" + id + "'", Productsubcategory.findProductsubcategory(id));
    }
    
}
