// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Attribute;
import ch.emineo.roo.reverse.domain.AttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.Productthemecontentholder;
import ch.emineo.roo.reverse.domain.ProductthemecontentholderAttribute;
import ch.emineo.roo.reverse.domain.ProductthemecontentholderAttributeDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductthemecontentholderAttributePK;
import ch.emineo.roo.reverse.domain.ProductthemecontentholderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductthemecontentholderAttributeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductthemecontentholderAttributeDataOnDemand: @Component;
    
    private Random ProductthemecontentholderAttributeDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductthemecontentholderAttribute> ProductthemecontentholderAttributeDataOnDemand.data;
    
    @Autowired
    private AttributeDataOnDemand ProductthemecontentholderAttributeDataOnDemand.attributeDataOnDemand;
    
    @Autowired
    private ProductthemecontentholderDataOnDemand ProductthemecontentholderAttributeDataOnDemand.productthemecontentholderDataOnDemand;
    
    public ProductthemecontentholderAttribute ProductthemecontentholderAttributeDataOnDemand.getNewTransientProductthemecontentholderAttribute(int index) {
        ProductthemecontentholderAttribute obj = new ProductthemecontentholderAttribute();
        setEmbeddedIdClass(obj, index);
        setAttributesAttributeid(obj, index);
        setProductthemecontentholderProductthemecontentholderid(obj, index);
        return obj;
    }
    
    public void ProductthemecontentholderAttributeDataOnDemand.setEmbeddedIdClass(ProductthemecontentholderAttribute obj, int index) {
        Integer productthemecontentholderProductthemecontentholderid = new Integer(index);
        Integer idx = new Integer(index);
        
        ProductthemecontentholderAttributePK embeddedIdClass = new ProductthemecontentholderAttributePK(productthemecontentholderProductthemecontentholderid, idx);
        obj.setId(embeddedIdClass);
    }
    
    public void ProductthemecontentholderAttributeDataOnDemand.setAttributesAttributeid(ProductthemecontentholderAttribute obj, int index) {
        Attribute attributesAttributeid = attributeDataOnDemand.getRandomAttribute();
        obj.setAttributesAttributeid(attributesAttributeid);
    }
    
    public void ProductthemecontentholderAttributeDataOnDemand.setProductthemecontentholderProductthemecontentholderid(ProductthemecontentholderAttribute obj, int index) {
        Productthemecontentholder productthemecontentholderProductthemecontentholderid = productthemecontentholderDataOnDemand.getRandomProductthemecontentholder();
        obj.setProductthemecontentholderProductthemecontentholderid(productthemecontentholderProductthemecontentholderid);
    }
    
    public ProductthemecontentholderAttribute ProductthemecontentholderAttributeDataOnDemand.getSpecificProductthemecontentholderAttribute(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductthemecontentholderAttribute obj = data.get(index);
        ProductthemecontentholderAttributePK id = obj.getId();
        return ProductthemecontentholderAttribute.findProductthemecontentholderAttribute(id);
    }
    
    public ProductthemecontentholderAttribute ProductthemecontentholderAttributeDataOnDemand.getRandomProductthemecontentholderAttribute() {
        init();
        ProductthemecontentholderAttribute obj = data.get(rnd.nextInt(data.size()));
        ProductthemecontentholderAttributePK id = obj.getId();
        return ProductthemecontentholderAttribute.findProductthemecontentholderAttribute(id);
    }
    
    public boolean ProductthemecontentholderAttributeDataOnDemand.modifyProductthemecontentholderAttribute(ProductthemecontentholderAttribute obj) {
        return false;
    }
    
    public void ProductthemecontentholderAttributeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductthemecontentholderAttribute.findProductthemecontentholderAttributeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductthemecontentholderAttribute' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductthemecontentholderAttribute>();
        for (int i = 0; i < 10; i++) {
            ProductthemecontentholderAttribute obj = getNewTransientProductthemecontentholderAttribute(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
