// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductbuildelementIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductbuildelementIntegrationTest_Roo_Configurable {
    
    declare @type: ProductbuildelementIntegrationTest: @Configurable;
    
}
