// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productvariant;
import ch.emineo.roo.reverse.domain.ProductvariantDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductvariantIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductvariantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductvariantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductvariantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductvariantIntegrationTest: @Transactional;
    
    @Autowired
    private ProductvariantDataOnDemand ProductvariantIntegrationTest.dod;
    
    @Test
    public void ProductvariantIntegrationTest.testCountProductvariants() {
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", dod.getRandomProductvariant());
        long count = Productvariant.countProductvariants();
        Assert.assertTrue("Counter for 'Productvariant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductvariantIntegrationTest.testFindProductvariant() {
        Productvariant obj = dod.getRandomProductvariant();
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", obj);
        Integer id = obj.getProductvariantid();
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to provide an identifier", id);
        obj = Productvariant.findProductvariant(id);
        Assert.assertNotNull("Find method for 'Productvariant' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Productvariant' returned the incorrect identifier", id, obj.getProductvariantid());
    }
    
    @Test
    public void ProductvariantIntegrationTest.testFindAllProductvariants() {
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", dod.getRandomProductvariant());
        long count = Productvariant.countProductvariants();
        Assert.assertTrue("Too expensive to perform a find all test for 'Productvariant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Productvariant> result = Productvariant.findAllProductvariants();
        Assert.assertNotNull("Find all method for 'Productvariant' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Productvariant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductvariantIntegrationTest.testFindProductvariantEntries() {
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", dod.getRandomProductvariant());
        long count = Productvariant.countProductvariants();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Productvariant> result = Productvariant.findProductvariantEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Productvariant' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Productvariant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductvariantIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", dod.getRandomProductvariant());
        Productvariant obj = dod.getNewTransientProductvariant(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Productvariant' identifier to be null", obj.getProductvariantid());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Productvariant' identifier to no longer be null", obj.getProductvariantid());
    }
    
    @Test
    public void ProductvariantIntegrationTest.testRemove() {
        Productvariant obj = dod.getRandomProductvariant();
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to initialize correctly", obj);
        Integer id = obj.getProductvariantid();
        Assert.assertNotNull("Data on demand for 'Productvariant' failed to provide an identifier", id);
        obj = Productvariant.findProductvariant(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Productvariant' with identifier '" + id + "'", Productvariant.findProductvariant(id));
    }
    
}
