// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductbuildProductbuildelement;
import ch.emineo.roo.reverse.domain.ProductbuildProductbuildelementDataOnDemand;
import ch.emineo.roo.reverse.domain.ProductbuildProductbuildelementIntegrationTest;
import ch.emineo.roo.reverse.domain.ProductbuildProductbuildelementPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductbuildProductbuildelementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductbuildProductbuildelementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductbuildProductbuildelementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductbuildProductbuildelementIntegrationTest: @Transactional;
    
    @Autowired
    private ProductbuildProductbuildelementDataOnDemand ProductbuildProductbuildelementIntegrationTest.dod;
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testCountProductbuildProductbuildelements() {
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", dod.getRandomProductbuildProductbuildelement());
        long count = ProductbuildProductbuildelement.countProductbuildProductbuildelements();
        Assert.assertTrue("Counter for 'ProductbuildProductbuildelement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testFindProductbuildProductbuildelement() {
        ProductbuildProductbuildelement obj = dod.getRandomProductbuildProductbuildelement();
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", obj);
        ProductbuildProductbuildelementPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to provide an identifier", id);
        obj = ProductbuildProductbuildelement.findProductbuildProductbuildelement(id);
        Assert.assertNotNull("Find method for 'ProductbuildProductbuildelement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductbuildProductbuildelement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testFindAllProductbuildProductbuildelements() {
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", dod.getRandomProductbuildProductbuildelement());
        long count = ProductbuildProductbuildelement.countProductbuildProductbuildelements();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductbuildProductbuildelement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductbuildProductbuildelement> result = ProductbuildProductbuildelement.findAllProductbuildProductbuildelements();
        Assert.assertNotNull("Find all method for 'ProductbuildProductbuildelement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductbuildProductbuildelement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testFindProductbuildProductbuildelementEntries() {
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", dod.getRandomProductbuildProductbuildelement());
        long count = ProductbuildProductbuildelement.countProductbuildProductbuildelements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductbuildProductbuildelement> result = ProductbuildProductbuildelement.findProductbuildProductbuildelementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductbuildProductbuildelement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductbuildProductbuildelement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", dod.getRandomProductbuildProductbuildelement());
        ProductbuildProductbuildelement obj = dod.getNewTransientProductbuildProductbuildelement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductbuildProductbuildelement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductbuildProductbuildelementIntegrationTest.testRemove() {
        ProductbuildProductbuildelement obj = dod.getRandomProductbuildProductbuildelement();
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to initialize correctly", obj);
        ProductbuildProductbuildelementPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductbuildProductbuildelement' failed to provide an identifier", id);
        obj = ProductbuildProductbuildelement.findProductbuildProductbuildelement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductbuildProductbuildelement' with identifier '" + id + "'", ProductbuildProductbuildelement.findProductbuildProductbuildelement(id));
    }
    
}
