// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Product;
import ch.emineo.roo.reverse.domain.ProductDataOnDemand;
import ch.emineo.roo.reverse.domain.Producttheme;
import ch.emineo.roo.reverse.domain.ProductthemeDataOnDemand;
import ch.emineo.roo.reverse.domain.Promotion;
import ch.emineo.roo.reverse.domain.PromotionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PromotionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PromotionDataOnDemand: @Component;
    
    private Random PromotionDataOnDemand.rnd = new SecureRandom();
    
    private List<Promotion> PromotionDataOnDemand.data;
    
    @Autowired
    private ProductDataOnDemand PromotionDataOnDemand.productDataOnDemand;
    
    @Autowired
    private ProductthemeDataOnDemand PromotionDataOnDemand.productthemeDataOnDemand;
    
    public Promotion PromotionDataOnDemand.getNewTransientPromotion(int index) {
        Promotion obj = new Promotion();
        setOnline(obj, index);
        setProductProductid(obj, index);
        setProductthemeProductthemeid(obj, index);
        setPromotionend(obj, index);
        setPromotionname(obj, index);
        setPromotionstart(obj, index);
        setPublic1(obj, index);
        return obj;
    }
    
    public void PromotionDataOnDemand.setOnline(Promotion obj, int index) {
        Boolean online = true;
        obj.setOnline(online);
    }
    
    public void PromotionDataOnDemand.setProductProductid(Promotion obj, int index) {
        Product productProductid = productDataOnDemand.getRandomProduct();
        obj.setProductProductid(productProductid);
    }
    
    public void PromotionDataOnDemand.setProductthemeProductthemeid(Promotion obj, int index) {
        Producttheme productthemeProductthemeid = productthemeDataOnDemand.getRandomProducttheme();
        obj.setProductthemeProductthemeid(productthemeProductthemeid);
    }
    
    public void PromotionDataOnDemand.setPromotionend(Promotion obj, int index) {
        Date promotionend = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPromotionend(promotionend);
    }
    
    public void PromotionDataOnDemand.setPromotionname(Promotion obj, int index) {
        String promotionname = "promotionname_" + index;
        if (promotionname.length() > 255) {
            promotionname = promotionname.substring(0, 255);
        }
        obj.setPromotionname(promotionname);
    }
    
    public void PromotionDataOnDemand.setPromotionstart(Promotion obj, int index) {
        Date promotionstart = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPromotionstart(promotionstart);
    }
    
    public void PromotionDataOnDemand.setPublic1(Promotion obj, int index) {
        Boolean public1 = true;
        obj.setPublic1(public1);
    }
    
    public Promotion PromotionDataOnDemand.getSpecificPromotion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Promotion obj = data.get(index);
        Integer id = obj.getPromotionid();
        return Promotion.findPromotion(id);
    }
    
    public Promotion PromotionDataOnDemand.getRandomPromotion() {
        init();
        Promotion obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getPromotionid();
        return Promotion.findPromotion(id);
    }
    
    public boolean PromotionDataOnDemand.modifyPromotion(Promotion obj) {
        return false;
    }
    
    public void PromotionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Promotion.findPromotionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Promotion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Promotion>();
        for (int i = 0; i < 10; i++) {
            Promotion obj = getNewTransientPromotion(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
