// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Promotioncode;
import ch.emineo.roo.reverse.domain.PromotioncodeDataOnDemand;
import ch.emineo.roo.reverse.domain.PromotioncodeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PromotioncodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PromotioncodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PromotioncodeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PromotioncodeIntegrationTest: @Transactional;
    
    @Autowired
    private PromotioncodeDataOnDemand PromotioncodeIntegrationTest.dod;
    
    @Test
    public void PromotioncodeIntegrationTest.testCountPromotioncodes() {
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", dod.getRandomPromotioncode());
        long count = Promotioncode.countPromotioncodes();
        Assert.assertTrue("Counter for 'Promotioncode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PromotioncodeIntegrationTest.testFindPromotioncode() {
        Promotioncode obj = dod.getRandomPromotioncode();
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", obj);
        String id = obj.getPromotioncodeid();
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to provide an identifier", id);
        obj = Promotioncode.findPromotioncode(id);
        Assert.assertNotNull("Find method for 'Promotioncode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Promotioncode' returned the incorrect identifier", id, obj.getPromotioncodeid());
    }
    
    @Test
    public void PromotioncodeIntegrationTest.testFindAllPromotioncodes() {
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", dod.getRandomPromotioncode());
        long count = Promotioncode.countPromotioncodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Promotioncode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Promotioncode> result = Promotioncode.findAllPromotioncodes();
        Assert.assertNotNull("Find all method for 'Promotioncode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Promotioncode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PromotioncodeIntegrationTest.testFindPromotioncodeEntries() {
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", dod.getRandomPromotioncode());
        long count = Promotioncode.countPromotioncodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Promotioncode> result = Promotioncode.findPromotioncodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Promotioncode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Promotioncode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PromotioncodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", dod.getRandomPromotioncode());
        Promotioncode obj = dod.getNewTransientPromotioncode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Promotioncode' identifier to be null", obj.getPromotioncodeid());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Promotioncode' identifier to no longer be null", obj.getPromotioncodeid());
    }
    
    @Test
    public void PromotioncodeIntegrationTest.testRemove() {
        Promotioncode obj = dod.getRandomPromotioncode();
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to initialize correctly", obj);
        String id = obj.getPromotioncodeid();
        Assert.assertNotNull("Data on demand for 'Promotioncode' failed to provide an identifier", id);
        obj = Promotioncode.findPromotioncode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Promotioncode' with identifier '" + id + "'", Promotioncode.findPromotioncode(id));
    }
    
}
