// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.UserTransaction;
import ch.emineo.roo.reverse.domain.UserTransactionDataOnDemand;
import ch.emineo.roo.reverse.domain.UserTransactionIntegrationTest;
import ch.emineo.roo.reverse.domain.UserTransactionPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserTransactionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserTransactionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserTransactionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserTransactionIntegrationTest: @Transactional;
    
    @Autowired
    private UserTransactionDataOnDemand UserTransactionIntegrationTest.dod;
    
    @Test
    public void UserTransactionIntegrationTest.testCountUserTransactions() {
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", dod.getRandomUserTransaction());
        long count = UserTransaction.countUserTransactions();
        Assert.assertTrue("Counter for 'UserTransaction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserTransactionIntegrationTest.testFindUserTransaction() {
        UserTransaction obj = dod.getRandomUserTransaction();
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", obj);
        UserTransactionPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to provide an identifier", id);
        obj = UserTransaction.findUserTransaction(id);
        Assert.assertNotNull("Find method for 'UserTransaction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserTransaction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserTransactionIntegrationTest.testFindAllUserTransactions() {
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", dod.getRandomUserTransaction());
        long count = UserTransaction.countUserTransactions();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserTransaction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserTransaction> result = UserTransaction.findAllUserTransactions();
        Assert.assertNotNull("Find all method for 'UserTransaction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserTransaction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserTransactionIntegrationTest.testFindUserTransactionEntries() {
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", dod.getRandomUserTransaction());
        long count = UserTransaction.countUserTransactions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserTransaction> result = UserTransaction.findUserTransactionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserTransaction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserTransaction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserTransactionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", dod.getRandomUserTransaction());
        UserTransaction obj = dod.getNewTransientUserTransaction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserTransaction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserTransactionIntegrationTest.testRemove() {
        UserTransaction obj = dod.getRandomUserTransaction();
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to initialize correctly", obj);
        UserTransactionPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserTransaction' failed to provide an identifier", id);
        obj = UserTransaction.findUserTransaction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserTransaction' with identifier '" + id + "'", UserTransaction.findUserTransaction(id));
    }
    
}
