// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Productthemecontentholder;
import ch.emineo.roo.reverse.domain.Productthemesubcategory;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholder;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect ProductthemesubcategoryProductthemecontentholder_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "PRODUCTTHEMESUBCATEGORY_PRODUCTTHEMESUBCATEGORYID", referencedColumnName = "PRODUCTTHEMESUBCATEGORYID", nullable = false, insertable = false, updatable = false)
    private Productthemesubcategory ProductthemesubcategoryProductthemecontentholder.productthemesubcategoryProductthemesubcategoryid;
    
    @ManyToOne
    @JoinColumn(name = "PRODUCTTHEMECONTENTHOLDERS_PRODUCTTHEMECONTENTHOLDERID", referencedColumnName = "PRODUCTTHEMECONTENTHOLDERID", nullable = false)
    private Productthemecontentholder ProductthemesubcategoryProductthemecontentholder.productthemecontentholdersProductthemecontentholderid;
    
    public Productthemesubcategory ProductthemesubcategoryProductthemecontentholder.getProductthemesubcategoryProductthemesubcategoryid() {
        return productthemesubcategoryProductthemesubcategoryid;
    }
    
    public void ProductthemesubcategoryProductthemecontentholder.setProductthemesubcategoryProductthemesubcategoryid(Productthemesubcategory productthemesubcategoryProductthemesubcategoryid) {
        this.productthemesubcategoryProductthemesubcategoryid = productthemesubcategoryProductthemesubcategoryid;
    }
    
    public Productthemecontentholder ProductthemesubcategoryProductthemecontentholder.getProductthemecontentholdersProductthemecontentholderid() {
        return productthemecontentholdersProductthemecontentholderid;
    }
    
    public void ProductthemesubcategoryProductthemecontentholder.setProductthemecontentholdersProductthemecontentholderid(Productthemecontentholder productthemecontentholdersProductthemecontentholderid) {
        this.productthemecontentholdersProductthemecontentholderid = productthemecontentholdersProductthemecontentholderid;
    }
    
}
