// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemesubcategoryAttributePK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect ProductthemesubcategoryAttributePK_Roo_Json {
    
    public String ProductthemesubcategoryAttributePK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static ProductthemesubcategoryAttributePK ProductthemesubcategoryAttributePK.fromJsonToProductthemesubcategoryAttributePK(String json) {
        return new JSONDeserializer<ProductthemesubcategoryAttributePK>().use(null, ProductthemesubcategoryAttributePK.class).deserialize(json);
    }
    
    public static String ProductthemesubcategoryAttributePK.toJsonArray(Collection<ProductthemesubcategoryAttributePK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<ProductthemesubcategoryAttributePK> ProductthemesubcategoryAttributePK.fromJsonArrayToProductthemesubcategoryAttributePKs(String json) {
        return new JSONDeserializer<List<ProductthemesubcategoryAttributePK>>().use(null, ArrayList.class).use("values", ProductthemesubcategoryAttributePK.class).deserialize(json);
    }
    
}
