// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemecategoryProductthemesubcategory;
import ch.emineo.roo.reverse.domain.ProductthemecategoryProductthemesubcategoryPK;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductthemecategoryProductthemesubcategory_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductthemecategoryProductthemesubcategory.entityManager;
    
    public static final EntityManager ProductthemecategoryProductthemesubcategory.entityManager() {
        EntityManager em = new ProductthemecategoryProductthemesubcategory().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductthemecategoryProductthemesubcategory.countProductthemecategoryProductthemesubcategorys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductthemecategoryProductthemesubcategory o", Long.class).getSingleResult();
    }
    
    public static List<ProductthemecategoryProductthemesubcategory> ProductthemecategoryProductthemesubcategory.findAllProductthemecategoryProductthemesubcategorys() {
        return entityManager().createQuery("SELECT o FROM ProductthemecategoryProductthemesubcategory o", ProductthemecategoryProductthemesubcategory.class).getResultList();
    }
    
    public static ProductthemecategoryProductthemesubcategory ProductthemecategoryProductthemesubcategory.findProductthemecategoryProductthemesubcategory(ProductthemecategoryProductthemesubcategoryPK id) {
        if (id == null) return null;
        return entityManager().find(ProductthemecategoryProductthemesubcategory.class, id);
    }
    
    public static List<ProductthemecategoryProductthemesubcategory> ProductthemecategoryProductthemesubcategory.findProductthemecategoryProductthemesubcategoryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductthemecategoryProductthemesubcategory o", ProductthemecategoryProductthemesubcategory.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductthemecategoryProductthemesubcategory.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductthemecategoryProductthemesubcategory.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductthemecategoryProductthemesubcategory attached = ProductthemecategoryProductthemesubcategory.findProductthemecategoryProductthemesubcategory(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductthemecategoryProductthemesubcategory.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductthemecategoryProductthemesubcategory.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductthemecategoryProductthemesubcategory ProductthemecategoryProductthemesubcategory.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductthemecategoryProductthemesubcategory merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
