// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemeProductthemecategory;
import ch.emineo.roo.reverse.domain.ProductthemeProductthemecategoryPK;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductthemeProductthemecategory_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductthemeProductthemecategory.entityManager;
    
    public static final EntityManager ProductthemeProductthemecategory.entityManager() {
        EntityManager em = new ProductthemeProductthemecategory().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductthemeProductthemecategory.countProductthemeProductthemecategorys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductthemeProductthemecategory o", Long.class).getSingleResult();
    }
    
    public static List<ProductthemeProductthemecategory> ProductthemeProductthemecategory.findAllProductthemeProductthemecategorys() {
        return entityManager().createQuery("SELECT o FROM ProductthemeProductthemecategory o", ProductthemeProductthemecategory.class).getResultList();
    }
    
    public static ProductthemeProductthemecategory ProductthemeProductthemecategory.findProductthemeProductthemecategory(ProductthemeProductthemecategoryPK id) {
        if (id == null) return null;
        return entityManager().find(ProductthemeProductthemecategory.class, id);
    }
    
    public static List<ProductthemeProductthemecategory> ProductthemeProductthemecategory.findProductthemeProductthemecategoryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductthemeProductthemecategory o", ProductthemeProductthemecategory.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductthemeProductthemecategory.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductthemeProductthemecategory.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductthemeProductthemecategory attached = ProductthemeProductthemecategory.findProductthemeProductthemecategory(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductthemeProductthemecategory.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductthemeProductthemecategory.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductthemeProductthemecategory ProductthemeProductthemecategory.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductthemeProductthemecategory merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
