// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholderPK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect ProductthemesubcategoryProductthemecontentholderPK_Roo_Json {
    
    public String ProductthemesubcategoryProductthemecontentholderPK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static ProductthemesubcategoryProductthemecontentholderPK ProductthemesubcategoryProductthemecontentholderPK.fromJsonToProductthemesubcategoryProductthemecontentholderPK(String json) {
        return new JSONDeserializer<ProductthemesubcategoryProductthemecontentholderPK>().use(null, ProductthemesubcategoryProductthemecontentholderPK.class).deserialize(json);
    }
    
    public static String ProductthemesubcategoryProductthemecontentholderPK.toJsonArray(Collection<ProductthemesubcategoryProductthemecontentholderPK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<ProductthemesubcategoryProductthemecontentholderPK> ProductthemesubcategoryProductthemecontentholderPK.fromJsonArrayToProductthemesubcategoryProductthemecontentholderPKs(String json) {
        return new JSONDeserializer<List<ProductthemesubcategoryProductthemecontentholderPK>>().use(null, ArrayList.class).use("values", ProductthemesubcategoryProductthemecontentholderPK.class).deserialize(json);
    }
    
}
