// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemecategoryProductthemesubcategoryPK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect ProductthemecategoryProductthemesubcategoryPK_Roo_Json {
    
    public String ProductthemecategoryProductthemesubcategoryPK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static ProductthemecategoryProductthemesubcategoryPK ProductthemecategoryProductthemesubcategoryPK.fromJsonToProductthemecategoryProductthemesubcategoryPK(String json) {
        return new JSONDeserializer<ProductthemecategoryProductthemesubcategoryPK>().use(null, ProductthemecategoryProductthemesubcategoryPK.class).deserialize(json);
    }
    
    public static String ProductthemecategoryProductthemesubcategoryPK.toJsonArray(Collection<ProductthemecategoryProductthemesubcategoryPK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<ProductthemecategoryProductthemesubcategoryPK> ProductthemecategoryProductthemesubcategoryPK.fromJsonArrayToProductthemecategoryProductthemesubcategoryPKs(String json) {
        return new JSONDeserializer<List<ProductthemecategoryProductthemesubcategoryPK>>().use(null, ArrayList.class).use("values", ProductthemecategoryProductthemesubcategoryPK.class).deserialize(json);
    }
    
}
