// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.Producttheme;
import ch.emineo.roo.reverse.domain.ProductthemeProductthemecategory;
import ch.emineo.roo.reverse.domain.Productthemecategory;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect ProductthemeProductthemecategory_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "PRODUCTTHEME_PRODUCTTHEMEID", referencedColumnName = "PRODUCTTHEMEID", nullable = false, insertable = false, updatable = false)
    private Producttheme ProductthemeProductthemecategory.productthemeProductthemeid;
    
    @ManyToOne
    @JoinColumn(name = "PRODUCTTHEMECATEGORIES_PRODUCTTHEMECATEGORYID", referencedColumnName = "PRODUCTTHEMECATEGORYID", nullable = false)
    private Productthemecategory ProductthemeProductthemecategory.productthemecategoriesProductthemecategoryid;
    
    public Producttheme ProductthemeProductthemecategory.getProductthemeProductthemeid() {
        return productthemeProductthemeid;
    }
    
    public void ProductthemeProductthemecategory.setProductthemeProductthemeid(Producttheme productthemeProductthemeid) {
        this.productthemeProductthemeid = productthemeProductthemeid;
    }
    
    public Productthemecategory ProductthemeProductthemecategory.getProductthemecategoriesProductthemecategoryid() {
        return productthemecategoriesProductthemecategoryid;
    }
    
    public void ProductthemeProductthemecategory.setProductthemecategoriesProductthemecategoryid(Productthemecategory productthemecategoriesProductthemecategoryid) {
        this.productthemecategoriesProductthemecategoryid = productthemecategoriesProductthemecategoryid;
    }
    
}
