// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategory;
import ch.emineo.roo.reverse.domain.ProductcategoryProductsubcategoryPK;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductcategoryProductsubcategory_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductcategoryProductsubcategory.entityManager;
    
    public static final EntityManager ProductcategoryProductsubcategory.entityManager() {
        EntityManager em = new ProductcategoryProductsubcategory().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductcategoryProductsubcategory.countProductcategoryProductsubcategorys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductcategoryProductsubcategory o", Long.class).getSingleResult();
    }
    
    public static List<ProductcategoryProductsubcategory> ProductcategoryProductsubcategory.findAllProductcategoryProductsubcategorys() {
        return entityManager().createQuery("SELECT o FROM ProductcategoryProductsubcategory o", ProductcategoryProductsubcategory.class).getResultList();
    }
    
    public static ProductcategoryProductsubcategory ProductcategoryProductsubcategory.findProductcategoryProductsubcategory(ProductcategoryProductsubcategoryPK id) {
        if (id == null) return null;
        return entityManager().find(ProductcategoryProductsubcategory.class, id);
    }
    
    public static List<ProductcategoryProductsubcategory> ProductcategoryProductsubcategory.findProductcategoryProductsubcategoryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductcategoryProductsubcategory o", ProductcategoryProductsubcategory.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductcategoryProductsubcategory.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductcategoryProductsubcategory.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductcategoryProductsubcategory attached = ProductcategoryProductsubcategory.findProductcategoryProductsubcategory(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductcategoryProductsubcategory.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductcategoryProductsubcategory.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductcategoryProductsubcategory ProductcategoryProductsubcategory.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductcategoryProductsubcategory merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
