// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductbuildProductbuildelementPK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect ProductbuildProductbuildelementPK_Roo_Json {
    
    public String ProductbuildProductbuildelementPK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static ProductbuildProductbuildelementPK ProductbuildProductbuildelementPK.fromJsonToProductbuildProductbuildelementPK(String json) {
        return new JSONDeserializer<ProductbuildProductbuildelementPK>().use(null, ProductbuildProductbuildelementPK.class).deserialize(json);
    }
    
    public static String ProductbuildProductbuildelementPK.toJsonArray(Collection<ProductbuildProductbuildelementPK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<ProductbuildProductbuildelementPK> ProductbuildProductbuildelementPK.fromJsonArrayToProductbuildProductbuildelementPKs(String json) {
        return new JSONDeserializer<List<ProductbuildProductbuildelementPK>>().use(null, ArrayList.class).use("values", ProductbuildProductbuildelementPK.class).deserialize(json);
    }
    
}
