// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemecontentholderAttributePK;
import javax.persistence.Column;
import javax.persistence.Embeddable;

privileged aspect ProductthemecontentholderAttributePK_Roo_Identifier {
    
    declare @type: ProductthemecontentholderAttributePK: @Embeddable;
    
    @Column(name = "PRODUCTTHEMECONTENTHOLDER_PRODUCTTHEMECONTENTHOLDERID", nullable = false)
    private Integer ProductthemecontentholderAttributePK.productthemecontentholderProductthemecontentholderid;
    
    @Column(name = "IDX", nullable = false)
    private Integer ProductthemecontentholderAttributePK.idx;
    
    public ProductthemecontentholderAttributePK.new(Integer productthemecontentholderProductthemecontentholderid, Integer idx) {
        super();
        this.productthemecontentholderProductthemecontentholderid = productthemecontentholderProductthemecontentholderid;
        this.idx = idx;
    }

    private ProductthemecontentholderAttributePK.new() {
        super();
    }

    public Integer ProductthemecontentholderAttributePK.getProductthemecontentholderProductthemecontentholderid() {
        return productthemecontentholderProductthemecontentholderid;
    }
    
    public Integer ProductthemecontentholderAttributePK.getIdx() {
        return idx;
    }
    
}
