// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemecategoryProductthemesubcategory;
import ch.emineo.roo.reverse.domain.Productthemesubcategory;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryAttribute;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholder;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect Productthemesubcategory_Roo_DbManaged {
    
    @OneToMany(mappedBy = "productthemesubcategoriesProductthemesubcategoryid")
    private Set<ProductthemecategoryProductthemesubcategory> Productthemesubcategory.productthemecategoryProductthemesubcategories;
    
    @OneToMany(mappedBy = "productthemesubcategoryProductthemesubcategoryid")
    private Set<ProductthemesubcategoryAttribute> Productthemesubcategory.productthemesubcategoryAttributes;
    
    @OneToMany(mappedBy = "productthemesubcategoryProductthemesubcategoryid")
    private Set<ProductthemesubcategoryProductthemecontentholder> Productthemesubcategory.productthemesubcategoryProductthemecontentholders;
    
    @Column(name = "ONLINE")
    @NotNull
    private boolean Productthemesubcategory.online;
    
    @Column(name = "PUBLIC")
    @NotNull
    private boolean Productthemesubcategory.public1;
    
    public Set<ProductthemecategoryProductthemesubcategory> Productthemesubcategory.getProductthemecategoryProductthemesubcategories() {
        return productthemecategoryProductthemesubcategories;
    }
    
    public void Productthemesubcategory.setProductthemecategoryProductthemesubcategories(Set<ProductthemecategoryProductthemesubcategory> productthemecategoryProductthemesubcategories) {
        this.productthemecategoryProductthemesubcategories = productthemecategoryProductthemesubcategories;
    }
    
    public Set<ProductthemesubcategoryAttribute> Productthemesubcategory.getProductthemesubcategoryAttributes() {
        return productthemesubcategoryAttributes;
    }
    
    public void Productthemesubcategory.setProductthemesubcategoryAttributes(Set<ProductthemesubcategoryAttribute> productthemesubcategoryAttributes) {
        this.productthemesubcategoryAttributes = productthemesubcategoryAttributes;
    }
    
    public Set<ProductthemesubcategoryProductthemecontentholder> Productthemesubcategory.getProductthemesubcategoryProductthemecontentholders() {
        return productthemesubcategoryProductthemecontentholders;
    }
    
    public void Productthemesubcategory.setProductthemesubcategoryProductthemecontentholders(Set<ProductthemesubcategoryProductthemecontentholder> productthemesubcategoryProductthemecontentholders) {
        this.productthemesubcategoryProductthemecontentholders = productthemesubcategoryProductthemecontentholders;
    }
    
    public boolean Productthemesubcategory.isOnline() {
        return online;
    }
    
    public void Productthemesubcategory.setOnline(boolean online) {
        this.online = online;
    }
    
    public boolean Productthemesubcategory.isPublic1() {
        return public1;
    }
    
    public void Productthemesubcategory.setPublic1(boolean public1) {
        this.public1 = public1;
    }
    
}
