// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemesubcategoryAttribute;
import ch.emineo.roo.reverse.domain.ProductthemesubcategoryAttributePK;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductthemesubcategoryAttribute_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductthemesubcategoryAttribute.entityManager;
    
    public static final EntityManager ProductthemesubcategoryAttribute.entityManager() {
        EntityManager em = new ProductthemesubcategoryAttribute().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductthemesubcategoryAttribute.countProductthemesubcategoryAttributes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductthemesubcategoryAttribute o", Long.class).getSingleResult();
    }
    
    public static List<ProductthemesubcategoryAttribute> ProductthemesubcategoryAttribute.findAllProductthemesubcategoryAttributes() {
        return entityManager().createQuery("SELECT o FROM ProductthemesubcategoryAttribute o", ProductthemesubcategoryAttribute.class).getResultList();
    }
    
    public static ProductthemesubcategoryAttribute ProductthemesubcategoryAttribute.findProductthemesubcategoryAttribute(ProductthemesubcategoryAttributePK id) {
        if (id == null) return null;
        return entityManager().find(ProductthemesubcategoryAttribute.class, id);
    }
    
    public static List<ProductthemesubcategoryAttribute> ProductthemesubcategoryAttribute.findProductthemesubcategoryAttributeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductthemesubcategoryAttribute o", ProductthemesubcategoryAttribute.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductthemesubcategoryAttribute.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductthemesubcategoryAttribute.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductthemesubcategoryAttribute attached = ProductthemesubcategoryAttribute.findProductthemesubcategoryAttribute(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductthemesubcategoryAttribute.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductthemesubcategoryAttribute.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductthemesubcategoryAttribute ProductthemesubcategoryAttribute.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductthemesubcategoryAttribute merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
