// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.ProductthemesubcategoryProductthemecontentholderPK;
import javax.persistence.Column;
import javax.persistence.Embeddable;

privileged aspect ProductthemesubcategoryProductthemecontentholderPK_Roo_Identifier {
    
    declare @type: ProductthemesubcategoryProductthemecontentholderPK: @Embeddable;
    
    @Column(name = "PRODUCTTHEMESUBCATEGORY_PRODUCTTHEMESUBCATEGORYID", nullable = false)
    private Integer ProductthemesubcategoryProductthemecontentholderPK.productthemesubcategoryProductthemesubcategoryid;
    
    @Column(name = "IDX", nullable = false)
    private Integer ProductthemesubcategoryProductthemecontentholderPK.idx;
    
    public ProductthemesubcategoryProductthemecontentholderPK.new(Integer productthemesubcategoryProductthemesubcategoryid, Integer idx) {
        super();
        this.productthemesubcategoryProductthemesubcategoryid = productthemesubcategoryProductthemesubcategoryid;
        this.idx = idx;
    }

    private ProductthemesubcategoryProductthemecontentholderPK.new() {
        super();
    }

    public Integer ProductthemesubcategoryProductthemecontentholderPK.getProductthemesubcategoryProductthemesubcategoryid() {
        return productthemesubcategoryProductthemesubcategoryid;
    }
    
    public Integer ProductthemesubcategoryProductthemecontentholderPK.getIdx() {
        return idx;
    }
    
}
