// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.emineo.roo.reverse.domain;

import ch.emineo.roo.reverse.domain.UserRolePK;
import java.io.Serializable;

privileged aspect UserRolePK_Roo_Serializable {
    
    declare parents: UserRolePK implements Serializable;
    
    private static final long UserRolePK.serialVersionUID = 1L;
    
}
